### ISSUE TITLE
Crash with VanillaFix

### ISSUE THREAD

**Issue by magcicada** [LoliKingdom/MixinBooter#11]
Crash with VanillaFix mod because of the mixins.

**Comment by magcicada** [comment]
java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zzb001$beforeConstructingMods(Loader.java:1641)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Macleykun** [comment]
Same error, latest version of VanillaFix and mixinbooter (withoud mixincompat)

**Comment by juraj-hrivnak** [comment]
Here is a full crash log from my mod pack: https://pastebin.com/aajfk80S
