### ISSUE TITLE
8.0 on 1.12.2 java.lang.IllegalAccessError: on startup

### ISSUE THREAD

**Issue by InuYasha86000** [LoliKingdom/MixinBooter#32]
I do not believe I have the mod Redstone Arsenal and therefor I am making a separate crash report. the previous V7.1 works no problems.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-05-30 20:09:34 PDT
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zzb001$beforeConstructingMods(Loader.java:1641)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 998437960 bytes (952 MB) / 2124414976 bytes (2026 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9216m -Xms256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 203 mods loaded, 203 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                      | Version                         | Source                                                    | Signature                                |
       |:----- |:----------------------- |:------------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
       | L     | minecraft               | 1.12.2                          | minecraft.jar                                             | None                                     |
       | L     | mcp                     | 9.42                            | minecraft.jar                                             | None                                     |
       | L     | FML                     | 8.0.99.99                       | forge-1.12.2-14.23.5.2860.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | forge                   | 14.23.5.2860                    | forge-1.12.2-14.23.5.2860.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | L     | ColorUtility            | 1.0.4                           | minecraft.jar                                             | None                                     |
       | L     | creativecoredummy       | 1.0.0                           | minecraft.jar                                             | None                                     |
       | L     | littletilescore         | 1.0.0                           | minecraft.jar                                             | None                                     |
       | L     | mixinbooter             | 8.0                             | minecraft.jar                                             | None                                     |
       | L     | foamfixcore             | 7.7.4                           | minecraft.jar                                             | None                                     |
       | L     | obfuscate               | 0.4.2                           | minecraft.jar                                             | None                                     |
       | L     | itemblacklist           | 1.4.3                           | ItemBlacklist-1.4.3.jar                                   | None                                     |
       | L     | securitycraft           | v1.9.6                          | [1.12.2] SecurityCraft v1.9.6.jar                         | None                                     |
       | L     | additionalbanners       | 1.1.77                          | AdditionalBanners-1.12.2-1.1.77.jar                       | None                                     |
       | L     | aiimprovements          | 0.0.1.3                         | AIImprovements-1.12-0.0.1b3.jar                           | None                                     |
       | L     | mts                     | 22.10.0                         | Immersive+Vehicles-1.12.2-22.10.0.jar                     | None                                     |
       | L     | mtsaircooled            | 1.0.1                           | Air-Cooled Pack [MTS] 1.10.2-14.0.0-1.0.1.jar             | None                                     |
       | L     | ctm                     | MC1.12.2-1.0.2.31               | CTM-MC1.12.2-1.0.2.31.jar                                 | None                                     |
       | L     | appliedenergistics2     | rv6-stable-7                    | appliedenergistics2-rv6-stable-7.jar                      | None                                     |
       | L     | aquaacrobatics          | 1.15.3                          | AquaAcrobatics-1.15.3.jar                                 | None                                     |
       | L     | astikorcarts            | 1.12.2-0.1.2.8                  | astikorcarts-1.12.2-0.1.2.8.jar                           | None                                     |
       | L     | atlaslib                | 1.1.5a                          | Atlas-Lib-1.12.2-1.1.5a.jar                               | None                                     |
       | L     | attributefix            | 1.0.12                          | AttributeFix-Forge-1.12.2-1.0.12.jar                      | None                                     |
       | L     | bannerpatch             | 1.0.0                           | BannerPatch-1.0.0.jar                                     | None                                     |
       | L     | baubles                 | 1.5.2                           | Baubles-1.12-1.5.2.jar                                    | None                                     |
       | L     | baubleye                | 1.3.3                           | Baubley-Elytra-v1.3.3-mc1.12.2.jar                        | None                                     |
       | L     | betternether            | 0.1.8.6                         | betternether-0.1.8.6.jar                                  | None                                     |
       | L     | bibliocraft             | 2.4.6                           | BiblioCraft[v2.4.6][MC1.12.2].jar                         | None                                     |
       | L     | bigbeautifulbuttons     | 1.12.2-1.1.3                    | bigbeautifulbuttons-1.12.2-1.1.3.jar                      | None                                     |
       | L     | biggerpacketsplz        | 1.2                             | biggerpacketsplz-since1.8-1.2.jar                         | None                                     |
       | L     | biomesoplenty           | 7.0.1.2445                      | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar             | None                                     |
       | L     | codechickenlib          | 3.2.3.358                       | CodeChickenLib-1.12.2-3.2.3.358-universal.jar             | None                                     |
       | L     | redstoneflux            | 2.1.1                           | RedstoneFlux-1.12-2.1.1.1-universal.jar                   | None                                     |
       | L     | brandonscore            | 2.4.20                          | BrandonsCore-1.12.2-2.4.20.162-universal.jar              | None                                     |
       | L     | buildcraftlib           | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | buildcraftcore          | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | buildcraftbuilders      | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | buildcrafttransport     | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | buildcraftsilicon       | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | crafttweaker            | 4.1.20                          | CraftTweaker2-1.12-4.1.20.688.jar                         | None                                     |
       | L     | buildcraftenergy        | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | mtlib                   | 3.0.7                           | MTLib-3.0.7.jar                                           | None                                     |
       | L     | modtweaker              | 4.0.19                          | modtweaker-4.0.20.11.jar                                  | None                                     |
       | L     | jei                     | 4.16.1.1003                     | jei_1.12.2-4.16.1.1003.jar                                | None                                     |
       | L     | mantle                  | 1.12-1.3.3.55                   | Mantle-1.12-1.3.3.55.jar                                  | None                                     |
       | L     | natura                  | 1.12.2-4.3.2.69                 | natura-1.12.2-4.3.2.69.jar                                | None                                     |
       | L     | forestry                | 5.8.2.387                       | forestry_1.12.2-5.8.2.387.jar                             | None                                     |
       | L     | buildcraftcompat        | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | buildcraftfactory       | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | buildcraftrobotics      | 7.99.24.8                       | buildcraft-all-7.99.24.8.jar                              | None                                     |
       | L     | cardboardboxes          | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | cardboardboxes-1.12.2-0.0.4.jar                           | None                                     |
       | L     | casinocraft             | v11                             | CasinoCraft_1.12.2_v11.jar                                | None                                     |
       | L     | catwalks                | 1.12.2-4.0.45                   | catwalks-1.12.2-4.0.45.jar                                | None                                     |
       | L     | caves_and_cliffs        | 1.0.9                           | CC(FG1.12.2) 1.0.9.jar                                    | None                                     |
       | L     | chameleon               | 1.12-4.1.3                      | Chameleon-1.12-4.1.3.jar                                  | None                                     |
       | L     | chisel                  | MC1.12.2-1.0.2.45               | Chisel-MC1.12.2-1.0.2.45.jar                              | None                                     |
       | L     | cofhcore                | 4.6.6                           | CoFHCore-1.12.2-4.6.6.1-universal.jar                     | None                                     |
       | L     | cofhworld               | 1.4.0                           | CoFHWorld-1.12.2-1.4.0.1-universal.jar                    | None                                     |
       | L     | collective              | 3.0                             | collective-1.12.2-3.0.jar                                 | None                                     |
       | L     | coloredredstone         | 1.3.2                           | Colored Redstone-1.3.2.jar                                | None                                     |
       | L     | colored_water           | 1.12.2-b37                      | ColoredWater-1.12.2-b37.jar                               | None                                     |
       | L     | morpheus                | 1.12.2-3.5.106                  | Morpheus-1.12.2-3.5.106.jar                               | None                                     |
       | L     | comforts                | 1.4.1.3                         | comforts-1.12.2-1.4.1.3.jar                               | None                                     |
       | L     | cyclopscore             | 1.6.7                           | CyclopsCore-1.12.2-1.6.7.jar                              | None                                     |
       | L     | commoncapabilities      | 2.4.8                           | CommonCapabilities-1.12.2-2.4.8.jar                       | None                                     |
       | L     | tconstruct              | 1.12.2-2.13.0.183               | TConstruct-1.12.2-2.13.0.183.jar                          | None                                     |
       | L     | conarm                  | 1.2.5.10                        | conarm-1.12.2-1.2.5.10.jar                                | None                                     |
       | L     | controlling             | 3.0.10                          | Controlling-3.0.12.2.jar                                  | None                                     |
       | L     | cosmeticwood            | 1.1.1a                          | Cosmetic-Wood-1.12.2-1.1.1a.jar                           | None                                     |
       | L     | cosmeticbeds            | 1.12.2-1.0.2.2                  | cosmeticbeds-1.12.2-1.0.2.2.jar                           | None                                     |
       | L     | craftingtweaks          | 8.1.9                           | CraftingTweaks_1.12.2-8.1.9.jar                           | None                                     |
       | L     | ctgui                   | 1.0.0                           | CraftTweaker2-1.12-4.1.20.688.jar                         | None                                     |
       | L     | crafttweakerjei         | 2.0.3                           | CraftTweaker2-1.12-4.1.20.688.jar                         | None                                     |
       | L     | creativecore            | 1.10.0                          | CreativeCore_v1.10.70_mc1.12.2.jar                        | None                                     |
       | L     | criticalib              | 1.0.2                           | criticalib-1.0.2.jar                                      | None                                     |
       | L     | customizableelytra      | 1.0                             | Customizable-Elytra-v1.0-mc1.12.2.jar                     | None                                     |
       | L     | custommainmenu          | 2.0.9.1                         | CustomMainMenu-MC1.12.2-2.0.9.1.jar                       | None                                     |
       | L     | cxlibrary               | 1.6.1                           | cxlibrary-1.12.1-1.6.1.jar                                | None                                     |
       | L     | damageindicator         | 3.0.0                           | damageindicator-3.0.0.jar                                 | None                                     |
       | L     | debark                  | 0.1.3                           | Debark-0.1.3.jar                                          | None                                     |
       | L     | defaultlanport          | 1.0                             | Default LAN Port-1.0 1.12.2.jar                           | None                                     |
       | L     | journeymap              | 1.12.2-5.7.1                    | journeymap-1.12.2-5.7.1.jar                               | None                                     |
       | L     | defaultoptions          | 9.2.8                           | DefaultOptions_1.12.2-9.2.8.jar                           | None                                     |
       | L     | dragonmounts            | r46-40-gd9d9278                 | DragonMounts-r49-sunfork.jar                              | None                                     |
       | L     | storagedrawers          | 5.2.2                           | StorageDrawers-1.12.2-5.4.2.jar                           | None                                     |
       | L     | drawerfps               | 1.12.2-1.0.0                    | DrawerFPS-1.12.2-1.0.0.jar                                | None                                     |
       | L     | emojicord               | 1.1.1.39                        | Emojicord-1.12.2-1.1.1.39-universal.jar                   | None                                     |
       | L     | enderstorage            | 2.4.9                           | EnderStorage-1.12.2-2.4.9.jar                             | None                                     |
       | L     | railcraft               | 12.0.0                          | railcraft-12.0.0.jar                                      | None                                     |
       | L     | thermalfoundation       | 2.6.7                           | ThermalFoundation-1.12.2-2.6.7.1-universal.jar            | None                                     |
       | L     | immersiveengineering    | 0.12-98                         | ImmersiveEngineering-0.12-98.jar                          | None                                     |
       | L     | engineersdoors          | 0.9.1                           | engineers_doors-1.12.2-0.9.1.jar                          | None                                     |
       | L     | exoticbirds             | 1.0                             | Exotic Birds 1.12.2-3.2.0.jar                             | None                                     |
       | L     | extraanvils             | @VERSION@                       | extraanvils-0.9.jar                                       | None                                     |
       | L     | extrautils2             | 1.0                             | extrautils2-1.12-1.9.9.jar                                | None                                     |
       | L     | floodlights             | 1.4.4-22                        | FloodLights-1.12.2-1.4.4-22.jar                           | None                                     |
       | L     | fluidlogged_api         | 2.2.2                           | Fluidlogged-API-v2.2.2-mc1.12.2.jar                       | None                                     |
       | L     | foamfix                 | @VERSION@                       | foamfix-0.10.15-1.12.2.jar                                | None                                     |
       | L     | forgeendertech          | 1.12.2-4.5.6.1                  | ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar              | None                                     |
       | L     | forgelin                | 1.8.4                           | Forgelin-1.8.4.jar                                        | None                                     |
       | L     | framedcompactdrawers    | 1.2.7                           | framedcompactdrawers-1.2.7.jar                            | None                                     |
       | L     | furenikusroads          | 1.2.2                           | Furenikus_Roads-1.2.2.jar                                 | None                                     |
       | L     | cfm                     | 6.3.0                           | furniture-6.3.2-1.12.2.jar                                | None                                     |
       | L     | futuremc                | 0.2.6                           | future-mc-0.2.11.jar                                      | None                                     |
       | L     | gravestone              | 1.3.1                           | GraveStone-1.12.2-Graves-1.3.1.jar                        | None                                     |
       | L     | gravestone-extended     | 1.3.5.1                         | GraveStone-1.12.2-Extended-1.3.5.1.jar                    | None                                     |
       | L     | growflow2               | 0.1                             | GrowFlow2-1.12.2-0.4.jar                                  | None                                     |
       | L     | hammercore              | 2.0.6.32                        | HammerLib-1.12.2-2.0.6.32.jar                             | None                                     |
       | L     | waila                   | 1.8.26                          | Hwyla-1.8.26-B41_1.12.2.jar                               | None                                     |
       | L     | igwmod                  | 1.4.4-15                        | IGW-Mod-1.12.2-1.4.4-15-universal.jar                     | None                                     |
       | L     | mtsseagullmilitarypack  | 1.4.0                           | Immersive Vehicles (IV) Seagull's military pack 1.7.4.jar | None                                     |
       | L     | immersivecables         | 1.3.2                           | ImmersiveCables-1.12.2-1.3.2.jar                          | None                                     |
       | L     | immersivepetroleum      | 1.1.10                          | immersivepetroleum-1.12.2-1.1.10.jar                      | None                                     |
       | L     | immersiveposts          | 0.2.1                           | ImmersivePosts-0.2.1.jar                                  | None                                     |
       | L     | trackapi                | 1.2                             | TrackAPI-1.2.jar                                          | None                                     |
       | L     | universalmodcore        | 1.1.4                           | UniversalModCore-1.12.2-forge-1.1.4-2b81e7.jar            | None                                     |
       | L     | immersiverailroading    | 1.9.1                           | ImmersiveRailroading-1.12.2-forge-1.9.1.jar               | None                                     |
       | L     | immersivetech           | 1.3.10                          | immersivetech-1.12-1.3.10.jar                             | None                                     |
       | L     | immersivetweaks         | 1.1.0                           | immersivetweaks-1.12.2-1.1.0.jar                          | None                                     |
       | L     | ironbackpacks           | 1.12.2-3.0.8-12                 | IronBackpacks-1.12.2-3.0.8-12.jar                         | None                                     |
       | L     | ironbookshelves         | 1.0.0                           | ironbookshelves(V1.2).jar                                 | None                                     |
       | L     | ironchest               | 1.12.2-7.0.67.844               | ironchest-1.12.2-7.0.72.847.jar                           | None                                     |
       | L     | irontanks               | 1.12.2-2.1.0-beta.18            | irontanks-1.12.2-2.1.0-beta.18.jar                        | None                                     |
       | L     | jepb                    | 1.2.1                           | jepb-1.12-1.2.1.jar                                       | None                                     |
       | L     | vehicle                 | 0.44.1                          | vehicle-mod-0.44.1-1.12.2.jar                             | None                                     |
       | L     | jev                     | 2.0.0                           | jev-1.12.2-2.0.0.jar                                      | None                                     |
       | L     | harvestcraft            | 1.12.2zb                        | Pam's HarvestCraft 1.12.2zg.jar                           | None                                     |
       | L     | jehc                    | 1.7.2                           | just-enough-harvestcraft-1.12.2-1.7.2.jar                 | None                                     |
       | L     | jeid                    | 1.0.4-SNAPSHOT                  | JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar                     | None                                     |
       | L     | kirosblocks             | 1.2.1                           | kirosblocks-1.2.1.jar                                     | None                                     |
       | L     | kleeslabs               | 5.4.12                          | KleeSlabs_1.12.2-5.4.12.jar                               | None                                     |
       | L     | littleframes            | 1.0.0                           | LittleFrames_v1.0.12_mc1.12.2.jar                         | None                                     |
       | L     | littleopener            | 1.0.1                           | littleopener-1.0.1.jar                                    | None                                     |
       | L     | littletiles             | 1.5.0                           | LittleTiles_v1.5.68_mc1.12.2.jar                          | None                                     |
       | L     | mcwbridges              | 1.0.6                           | mcw-bridges-1.0.6b-mc1.12.2.jar                           | None                                     |
       | L     | mcwdoors                | 1.3                             | mcw-doors-1.0.3-mc1.12.2.jar                              | None                                     |
       | L     | mcwfences               | 1.0.0                           | mcw-fences-1.0.0-mc1.12.2.jar                             | None                                     |
       | L     | mcwfurnitures           | 1.0.1                           | mcw-furniture-1.0.1-mc1.12.2beta.jar                      | None                                     |
       | L     | mcwroofs                | 1.0.2                           | mcw-roofs-1.0.2-mc1.12.2.jar                              | None                                     |
       | L     | mcwtrpdoors             | 1.0.2                           | mcw-trapdoors-1.0.3-mc1.12.2.jar                          | None                                     |
       | L     | mcwwindows              | 1.0                             | mcw-windows-1.0.0-mc1.12.2.jar                            | None                                     |
       | L     | moarboats               | 4.1.2.1                         | moarboats-1.12.2-4.1.2.1.jar                              | None                                     |
       | L     | moarsigns               | 6.0.0.11                        | MoarSigns-1.12.2-6.0.0.11.jar                             | None                                     |
       | L     | modifierkeyfix          | 1.0                             | ModifierKeyFix-1.0.jar                                    | None                                     |
       | L     | morebeautifulbuttons    | 1.12.2-1.7.3.20                 | morebeautifulbuttons-1.12.2-1.7.3.20.jar                  | None                                     |
       | L     | morebeautifulplates     | 1.12.2-1.1.4                    | morebeautifulplates-1.12.2-1.1.4.jar                      | None                                     |
       | L     | morefurnaces            | 1.10.5                          | MoreFurnaces-1.12.2-1.10.6.jar                            | None                                     |
       | L     | mrtjpcore               | 2.1.4.43                        | MrTJPCore-1.12.2-2.1.4.43-universal.jar                   | None                                     |
       | L     | netherportalfix         | 5.3.17                          | NetherPortalFix_1.12.1-5.3.17.jar                         | None                                     |
       | L     | nei                     | 2.4.3                           | NotEnoughItems-1.12.2-2.4.3.245-universal.jar             | None                                     |
       | L     | oreberries              | 0.5.0                           | oreberries-1.12.x-0.5.0.jar                               | None                                     |
       | L     | performant              | 1.12.2-1.5                      | performant-1.11.jar                                       | None                                     |
       | L     | redstonepaste           | 1.7.5                           | redstonepaste-mc1.12-1.7.5.jar                            | None                                     |
       | L     | resourceloader          | 1.5.3                           | ResourceLoader-MC1.12.1-1.5.3.jar                         | None                                     |
       | L     | rsgauges                | 1.2.8                           | rsgauges-1.12.2-1.2.8.jar                                 | None                                     |
       | L     | screenbrowser           | 2r                              | ScreenshotBrowser-1.12.2-2r.jar                           | None                                     |
       | L     | searedladder            | 1.1.2                           | Seared-Ladder-v1.1.2-mc1.12.2.jar                         | None                                     |
       | L     | signpost                | 1.08.5                          | signpost-1.12.2-1.08.5.jar                                | None                                     |
       | L     | flashlight              | 2.0.0                           | simpleFlashlight-2.0.0.jar                                | None                                     |
       | L     | thermalexpansion        | 5.5.7                           | ThermalExpansion-1.12.2-5.5.7.1-universal.jar             | None                                     |
       | L     | thermaldynamics         | 2.5.6                           | ThermalDynamics-1.12.2-2.5.6.1-universal.jar              | None                                     |
       | L     | simplyjetpacks          | 1.12.2-2.2.20.0                 | SimplyJetpacks2-1.12.2-2.2.20.0.jar                       | None                                     |
       | L     | solarflux               | 12.4.11                         | SolarFluxReborn-1.12.2-12.4.11.jar                        | None                                     |
       | L     | speedyhoppers           | 1.1.19                          | speedyhoppers-1.1.19.jar                                  | None                                     |
       | L     | speedyladders           | 1.1.3                           | speedyladders-1.12.2-8.jar                                | None                                     |
       | L     | stg                     | 1.12.2-1.2.3                    | stg-1.12.2-1.2.3.jar                                      | None                                     |
       | L     | storagedrawersunlimited | 1.12.2-1.3.1                    | StorageDrawersUnlimitedFixed-1.12.2-1.3.1.jar             | None                                     |
       | L     | surge                   | 2.0.77                          | Surge-1.12.2-2.0.77.jar                                   | None                                     |
       | L     | thermalcultivation      | 0.3.6                           | ThermalCultivation-1.12.2-0.3.6.1-universal.jar           | None                                     |
       | L     | thermalinnovation       | 0.3.6                           | ThermalInnovation-1.12.2-0.3.6.1-universal.jar            | None                                     |
       | L     | thermaltinkering        | 1.0                             | ThermalTinkering-1.12.2-2.0.1.jar                         | None                                     |
       | L     | thutcore                | 5.21.0                          | thutcore-1.12.2-5.21.0.jar                                | None                                     |
       | L     | thutcore_compat         | 1.0                             | thutcore-1.12.2-5.21.0.jar                                | None                                     |
       | L     | thuttech                | 6.1.6                           | thuttech-1.12.2-6.1.6.jar                                 | None                                     |
       | L     | tcomplement             | 1.12.2-0.4.3                    | TinkersComplement-1.12.2-0.4.3.jar                        | None                                     |
       | L     | tinkersoredictcache     | 1.0                             | TinkersOreDictCache-1.0.jar                               | None                                     |
       | L     | tinkertoolcasts         | 1.2                             | TinkerToolcasts-1.2.jar                                   | None                                     |
       | L     | tinkertoolleveling      | 1.12.2-1.1.0.DEV.b23e769        | TinkerToolLeveling-1.12.2-1.1.0.jar                       | None                                     |
       | L     | torchmaster             | 1.8.5.0                         | torchmaster_1.12.2-1.8.5.0.jar                            | None                                     |
       | L     | townbuilder             | 3.0.0                           | TownBuilder-1.12.2-3.0.0-universal.jar                    | None                                     |
       | L     | trafficcontrol          | 1.0.0                           | trafficcontrol-1.0.0.jar                                  | None                                     |
       | L     | travelersbackpack       | 1.0.35                          | TravelersBackpack-1.12.2-1.0.35.jar                       | None                                     |
       | L     | iv_tcp_v3               | 3.20.0                          | Trin Civil Pack-1.12.2-3.20.0.jar                         | None                                     |
       | L     | iv_tpp                  | 2.22.0                          | Trin Parts Pack-1.12.2-2.22.0.jar                         | None                                     |
       | L     | unifine                 | 1.12.2-0.1.0                    | Unifine-1.12.2-0.1.0.jar                                  | None                                     |
       | L     | unuparts                | 5.1.4                           | UNU Parts Pack [MTS] 1.12.2-21.3.0-5.1.4.jar              | None                                     |
       | L     | unucivil                | 5.3.2                           | UNU Civilian Pack [MTS] 1.12.2-21.3.0-5.3.2.jar           | None                                     |
       | L     | unumilitary             | 5.0.0                           | UNU Military Pack [MTS] 1.12.2-21.3.0-5.0.0.jar           | None                                     |
       | L     | vanillafix              | 1.0.10-150                      | VanillaFix-1.0.10-150.jar                                 | None                                     |
       | L     | violetacannons          | 1.0                             | violetacannons-1.0.jar                                    | None                                     |
       | L     | wailaharvestability     | 1.1.12                          | WailaHarvestability-mc1.12-1.1.12.jar                     | None                                     |
       | L     | wanionlib               | 1.12.2-2.9                      | WanionLib-1.12.2-2.9.jar                                  | None                                     |
       | L     | waterstrainer           | 3.3.0                           | WaterStrainer-1.12-3.3.0.jar                              | None                                     |
       | L     | wawla                   | 2.6.275                         | Wawla-1.12.2-2.6.275.jar                                  | None                                     |
       | L     | wolfarmor               | 3.8.0                           | WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar     | None                                     |
       | L     | worldedit               | 6.1.10                          | worldedit-forge-mc1.12.2-6.1.10-dist.jar                  | None                                     |
       | L     | worldeditcuife3         | 3.0.9                           | WorldEdit-CUI-FE3-1.12.2-3.0.9.jar                        | None                                     |
       | L     | worldedit_items         | 1.1.0                           | WorldEditItems-v.1.1.0-Forge-1.12.2.jar                   | None                                     |
       | L     | recipehandler           | 0.14                            | YARCF-0.14(1.12.2).jar                                    | None                                     |
       | L     | betteranimalsplus       | 9.0.1                           | betteranimalsplus-1.12.2-9.0.1.jar                        | None                                     |
       | L     | industrialwires         | 1.7-39                          | IndustrialWires-1.7-39.jar                                | None                                     |
       | L     | adchimneys              | 1.12.2-3.5.16.0                 | AdChimneys-1.12.2-3.5.16.0-build.0654.jar                 | None                                     |
       | L     | mysticallib             | 1.12.2-1.13.0                   | mysticallib-1.12.2-1.13.0.jar                             | None                                     |
       | L     | unidict                 | 1.12.2-3.0.10                   | UniDict-1.12.2-3.0.10.jar                                 | None                                     |
  Loaded coremods (and transformers): Baubley Elytra Plugin (Baubley-Elytra-v1.3.3-mc1.12.2.jar)
                                        git.jbredwards.baubleye.BaubleyElytra$Transformer
                                      WolfArmorCore (WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
                                        nihiltres.engineersdoors.common.asm.EngineersDoorsClassTransformer
                                      LoadingPlugin (AdChimneys-1.12.2-3.5.16.0-build.0654.jar)
                                        com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
                                      Aqua Acrobatics Transformer (AquaAcrobatics-1.15.3.jar)
                                        
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      Default LAN Port (Default LAN Port-1.0 1.12.2.jar)
                                        core.defaultlanport.coretransform.CoreTransformer
                                      Customizable Elytra Plugin (Customizable-Elytra-v1.0-mc1.12.2.jar)
                                        git.jbredwards.customizableelytra.asm.ASMHandler$Transformer
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
                                        wanion.unidict.core.UniDictCoreModTransformer
                                      Damage Indicator Core (damageindicator-3.0.0.jar)
                                        
                                      CriticaLib Core (criticalib-1.0.2.jar)
                                        
                                      EDFMLLoadingPlugin (stairdoors-1.5.jar)
                                        com.darkenchanter.stairdoors.asm.EDClassTransformer
                                      SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.6.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      MixinBooter (!mixinbooter-8.0.jar)
                                        
                                      ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
                                        com.Axeryok.ColorUtility.ColorUtilityTransformer
                                      EmojicordCorePlugin (Emojicord-1.12.2-1.1.1.39-universal.jar)
                                        net.teamfruit.emojicord.asm.EmojicordTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      TinkerToolcastsCore (TinkerToolcasts-1.2.jar)
                                        com.eugenearch.tinkertoolcasts.core.TConstructSmelteryHookTransformer
                                      FutureMC (future-mc-0.2.11.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.68_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      MixinLoader (BannerPatch-1.0.0.jar)
                                        
                                      Fluidlogged API Plugin (Fluidlogged-API-v2.2.2-mc1.12.2.jar)
                                        git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
                                        git.jbredwards.fluidlogged_api.mod.asm.transformers.TransformerLevelProperty
                                        git.jbredwards.fluidlogged_api.mod.asm.transformers.TransformerSmoothWater
                                      CoreMod (ForgeMixinFix-1.0.0.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar)
                                        
                                      HCASM (HammerLib-1.12.2-2.0.6.32.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      BiggerPacketsPlzCoreMod (biggerpacketsplz-since1.8-1.2.jar)
                                        net.elnounch.mc.biggerpacketsplz.BiggerPacketsPlzClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 532.03' Renderer: 'NVIDIA GeForce RTX 3060/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: forge-14.23.5.2860
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 532.03, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 5800X3D 8-Core Processor

**Comment by Rongmario** [comment]
Closed for #34
