### ISSUE TITLE
Ver. 8.1 crashes with Integrated Proxy

### ISSUE THREAD

**Issue by NobodyHere-rrr** [LoliKingdom/MixinBooter#33]
Integrated Proxy: https://www.curseforge.com/minecraft/mc-mods/integrated-proxy

---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Daisy, daisy...

Time: 2023-05-31 12:47:24 CST
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$integrated_proxy_1_12_1_0_14$beforeConstructingMods(ModMixinLoader.java:1139)
    at net.minecraftforge.fml.common.Loader.loadMods(ModMixinLoader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:7101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by Rongmario** [comment]
Yeah it seems to only be compatible with Mixin 0.8.3, might need to open a PR or patch or directly. Same with #30

**Comment by Rongmario** [comment]
Closed for #34
