### ISSUE TITLE
[Question] `.ClassCastException: org.spongepowered.asm.mixin.transformer.ext.extensions.ExtensionClassExporter cannot be cast to org.spongepowered.asm.mixin.transformer.ext.IExtension`

### ISSUE THREAD

**Issue by SettingDust** [LoliKingdom/MixinBooter#41]
The `ExtensionClassExporter` should implements `IExtension`. Why is this happened
I'm shadow the 2.0.0 beta.9 in mixinbooter 7.1
```
[12:36:02] [main/ERROR] [MixinBooter]: Unexpected error
java.lang.ClassCastException: org.spongepowered.asm.mixin.transformer.ext.extensions.ExtensionClassExporter cannot be cast to org.spongepowered.asm.mixin.transformer.ext.IExtension
	at com.llamalad7.mixinextras.utils.MixinInternals.addExtension(MixinInternals.java:109) ~[MixinInternals.class:?]
	at com.llamalad7.mixinextras.utils.MixinInternals.registerExtension(MixinInternals.java:91) ~[MixinInternals.class:?]
	at com.llamalad7.mixinextras.MixinExtrasBootstrap.initialize(MixinExtrasBootstrap.java:41) ~[MixinExtrasBootstrap.class:?]
	at com.llamalad7.mixinextras.MixinExtrasBootstrap.init(MixinExtrasBootstrap.java:25) ~[MixinExtrasBootstrap.class:?]
	at settingdust.liangmufixes.LiangMuFixesMixinLoader.getMixinConfigs(LiangMuFixesMixinLoader.java:15) ~[main/:?]
	at zone.rong.mixinbooter.MixinBooterPlugin.injectData(MixinBooterPlugin.java:112) [mixinbooter-7.1.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:150) [forgeSrc-1.12.2-14.23.5.2768.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_372]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_372]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_372]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_372]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
```

**Comment by SettingDust** [comment]
Fine with mixin booter 5.0 that without the WrapOperation from mixin extras. Maybe it can't init aagin.
But I can't using 8.0+ that will crash XD  https://github.com/LoliKingdom/MixinBooter/issues/39
I'll using 5.0 for now :)
