### ISSUE TITLE
MixinBooter 3.0 

### ISSUE THREAD

**Issue by XcelOrbit** [LoliKingdom/MixinBooter#5]
MixinBooter 3.0 causes a crash upon startup (Using JRE 8u311, no mods but MixinBooter, Forge 2859): 

[16:45:51] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_311]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_311]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_311]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_311]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by XcelOrbit** [comment]
It seemed that there was an issue between MixinBooter and Phosphour, and upon removing Phosphour, it worked perfectly.
