### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by Pabsb** [LoliKingdom/MixinBooter#6]
**Crash error message:**

The game crashed whilst initializing game
Error: java.lang.NoSuchFieldException: processor
Exit Code: -1

**Mods used:**
- Wynntils 1.10.5
- Indicatia 1.3.3 (Requires SteveKunG's Lib)
- SteveKunG's Lib 1.1.11 (Requires Mixinbooter 3.0)
- Mixinbooter 3.0

**Forge Version:**
14.23.5.2860

**Notes**:
Using mixinbooter 2.0 crashes as well but with just "Exit Code: 0" and no crash report.

**Crash log:**
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (mixinbooter-3.0.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.11.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 1/19/22 11:51 AM
Description: Initializing game

java.lang.NoSuchFieldException: processor
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at net.minecraftforge.fml.common.LoadController.handler$beforeConstructing$zza000(LoadController.java:550)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at net.minecraftforge.fml.common.LoadController.handler$beforeConstructing$zza000(LoadController.java:550)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 281460672 bytes (268 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version      | Source                            | Signature                                |
	|:----- |:--------------- |:------------ |:--------------------------------- |:---------------------------------------- |
	| L     | minecraft       | 1.12.2       | minecraft.jar                     | None                                     |
	| L     | mcp             | 9.42         | minecraft.jar                     | None                                     |
	| L     | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge           | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | mixinbooter     | 3.0          | minecraft.jar                     | None                                     |
	| L     | stevekung's_lib | 1.1.11       | SteveKunG's-Lib-1.12.2-1.1.11.jar | None                                     |
	| L     | indicatia       | 1.3.3        | Indicatia-1.12.2-1.3.3.jar        | None                                     |
	| L     | wynntils        | 1.10.5       | Wynntils-1.10.5_655-MC1.12.2.jar  | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (mixinbooter-3.0.jar)
  
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.11.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.23' Renderer: 'NVIDIA GeForce RTX 3080/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.23, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor `

**Comment by Rongmario** [comment]
Finally a full crash report, ty for the report.

**Comment by Pabsb** [comment]
Hope this helps to resolve the issues

**Comment by Pabsb** [comment]
When trying to launch only having MixinBooter 3.0 it leaves no crash report with exit code 0 but does leave this short log report so I hope it helps

`
[23:05:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:05:55] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:05:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:05:55] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[23:05:55] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-legacy\windows-x64\jre-legacy
[23:05:55] [main/INFO] [FML]: Searching C:\Users\Pablo\AppData\Roaming\.minecraft\mods for mods
[23:05:55] [main/INFO] [FML]: Searching C:\Users\Pablo\AppData\Roaming\.minecraft\mods\1.12.2 for mods
[23:05:55] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from mixinbooter-3.0.jar
[23:05:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:05:55] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[23:05:55] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:05:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:05:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:05:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:05:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:05:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[23:05:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:05:55] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by Rongmario** [comment]
noted

**Comment by Rongmario** [comment]
Should be fixed in https://github.com/LoliKingdom/MixinBooter/commit/c81f30e846353d75d5975170c6f7d7a72efff4ce
