### ISSUE TITLE
Crash on launch: IllegalAccessError: tried to access class MixinProcessor from class Loader

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/MixinBooter#7]
After updating from 3.0 -> 3.1 i can't load game anymore.
MC crashes early on load with this error:
```java
Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zza000$beforeConstructingMods(ModMixinLoader.java:1139)
```

Downgrading to 3.0 fixes this issue.
[debug.log](https://github.com/LoliKingdom/MixinBooter/files/7906154/debug-1.log.gz)

**Comment by Rongmario** [comment]
Seems like an incompatibility with Integrated Proxy. Can you try without it?

**Comment by Krutoy242** [comment]
Unf... I could try.

**Comment by Rongmario** [comment]
Thanks, much appreciated.

**Comment by Krutoy242** [comment]
I disabled **Integrated Proxy**, but have same error.
[debug.log](https://github.com/LoliKingdom/MixinBooter/files/7906250/debug.log)

**Comment by Rongmario** [comment]
Some other mod is doing the same hack as Integrated Proxy 💤 hmm, I'll try write a check for this.

**Comment by Krutoy242** [comment]
Im testing it on my modpack [E2E-E](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended). Since it hosted on CF, you can install it to test on, if it would help.

**Comment by Rongmario** [comment]
I'll do that, thanks

**Comment by tappaja666** [comment]
The new version crashes to me even if its the only mod installed and fresh install
[17:23:29] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:29] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:29] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:29] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[17:23:29] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at D:\Minecraft modaus\Install\runtime\jre-legacy\windows-x64\jre-legacy
[17:23:29] [main/INFO]: Searching D:\Minecraft modaus\Instances\h\mods for mods
[17:23:29] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from .mixinbooter-3.1.jar
[17:23:29] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:23:29] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterConsole:log:93]: [17:23:29] [mixin/ERROR] No mixin host service is available. Services: 
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: 
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:232)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:189)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:183)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:88)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at java.lang.Class.newInstance(Class.java:442)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: 
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:232)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:189)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:183)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:88)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Rongmario** [comment]
Should be fixed in https://github.com/LoliKingdom/MixinBooter/commit/cade0f9dfeb882600260b398b2ed90c71ceb3f6b, curse build uploading...

**Comment by Krutoy242** [comment]
New 3.2 version wouldn't help.
[debug.log](https://github.com/LoliKingdom/MixinBooter/files/7906587/debug.log)

**Comment by Rongmario** [comment]
Rename the mixinbooter you downloaded by removing the `.`  in front of it. I can't fix this other than doing that, this is other mods doing stupid stuff.

**Comment by Rongmario** [comment]
I hate mods doing stupid shit, I'll upload a thin jar.

**Comment by Rongmario** [comment]
@Krutoy242 can you distribute if I upload the file as an additional file?: https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files/3614763

**Comment by Krutoy242** [comment]
Oof, i don't know how to do that.
I'm using CurseForge launcher to select mods and it automatically download jar associated with this mod. I dont know how to select another file, other than main one.

**Comment by Rongmario** [comment]
It's fine, if that jar works for you I'll upload it as a separate version.

**Comment by Krutoy242** [comment]
Seems like problem fixed by itself.
Using `.mixinbooter-4.1` and load game fine.
