### ISSUE TITLE
Crash: No mixin host service is available

### ISSUE THREAD

**Issue by Rongmario** [LoliKingdom/MixinBooter#8]
<details><summary>Report:</summary>
<p>
[17:23:29] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:29] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:29] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:23:29] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[17:23:29] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at D:\Minecraft modaus\Install\runtime\jre-legacy\windows-x64\jre-legacy
[17:23:29] [main/INFO]: Searching D:\Minecraft modaus\Instances\h\mods for mods
[17:23:29] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from .mixinbooter-3.1.jar
[17:23:29] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:23:29] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterConsole:log:93]: [17:23:29] [mixin/ERROR] No mixin host service is available. Services: 
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: 
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:232)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:189)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:183)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:88)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at java.lang.Class.newInstance(Class.java:442)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[17:23:29] [main/INFO]: [org.spongepowered.asm.logging.LoggerAdapterAbstract:error:142]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.service.ServiceNotAvailableError: No mixin host service is available. Services: 
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.initService(MixinService.java:232)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getServiceInstance(MixinService.java:189)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getService(MixinService.java:183)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:88)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[17:23:29] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
_Originally posted by @tappaja666 in https://github.com/LoliKingdom/MixinBooter/issues/7#issuecomment-1017620073_
</p>
</details>

**Comment by Rongmario** [comment]
Fixed in https://github.com/LoliKingdom/MixinBooter/commit/cade0f9dfeb882600260b398b2ed90c71ceb3f6b
